// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbV7TTFwGM_0rAQW0m9NUiLnyDg2gNX7A',
    appId: '1:913651321849:web:a4de2393c8ce12dcf84b28',
    messagingSenderId: '913651321849',
    projectId: 'mes-pieces-app',
    authDomain: 'mes-pieces-app.firebaseapp.com',
    storageBucket: 'mes-pieces-app.appspot.com',
    measurementId: 'G-2HSRYWD7WP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmBZZZGhesgGfyHx4Af--em6ctAlz_X5I',
    appId: '1:913651321849:android:09bdf9e3b6b7dbfaf84b28',
    messagingSenderId: '913651321849',
    projectId: 'mes-pieces-app',
    storageBucket: 'mes-pieces-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA57h6bYrDVpEjBg3cPr7qN50Qu-Jcq-u0',
    appId: '1:913651321849:ios:98676cc808ffa810f84b28',
    messagingSenderId: '913651321849',
    projectId: 'mes-pieces-app',
    storageBucket: 'mes-pieces-app.appspot.com',
    iosClientId: '913651321849-id84pl43nnv9p6mfog5ks5nr4ji79j5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.mesPiecesClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA57h6bYrDVpEjBg3cPr7qN50Qu-Jcq-u0',
    appId: '1:913651321849:ios:98676cc808ffa810f84b28',
    messagingSenderId: '913651321849',
    projectId: 'mes-pieces-app',
    storageBucket: 'mes-pieces-app.appspot.com',
    iosClientId: '913651321849-id84pl43nnv9p6mfog5ks5nr4ji79j5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.mesPiecesClient',
  );
}
