class ListHelper {
  static const List<String> cryptosCategories = [
    "BAND PROTOL (BAND)",
    "BITCOIN (BTC)",
    "CARDANO (ADA)",
    "COSMOS (ATOM)",
    "DOGECOIN (DOGE)",
    "ETHERIUM CLASSIC",
    "ETHERIUM (ETH)",
    "BUSDT",
    "KOMODO (KMD)",
    "SOLANA (SOL)",
    "SMART CHAIN (BNB)",
    "TERA (LUNA)",
    "TEZOS (XRZ)",
    "TRON (TRX)",
    "USDT_TRC20 (Tether)",
    "USDT_ERC20",
    "USDC_TRX",
    "USDC_ETH",
    "ZILLIQA (ZIL)",
    "SHIBA INU",
  ];

  static const List<String> mobileMoneyOperators = [
    "Airtel money (RDCongo)",
    "Orange money (RDCongo)",
    "M-Pesa (RDCongo)",
    "Orange money (Mali)",
    "Moov money (Mali)",
    "Sama Money (Mali)",
    "Wave (Mali)",
    "Mobil money (Côte d'Ivoire)",
    "Moov money (Côte d'Ivoire)",
    "MTN money(Côte d'Ivoire)",
    "MTN (Benin)",
    "MOOVAFRICA (Benin)",
    "Celtic (Benin)",
    "Orange money (Cameroun)",
    "MTN money (Cameroun)",
  ];

  static const List<String> bankOperators = [
    "TMB",
    "Access bank",
    "RawBank",
    "Western union",
    "Equity bcdc",
  ];

  static const List<String> years = [
    "1980",
    "1981",
    "1982",
    "1983",
    "1984",
    "1985",
    "1986",
    "1987",
    "1988",
    "1989",
    "1990",
    "1991",
    "1992",
    "1993",
    "1994",
    "1995",
    "1996",
    "1997",
    "1998",
    "1999",
    "2000",
    "2001",
    "2002",
    "2003",
    "2004",
    "2005",
  ];


}