class ListHelper{

  List<String> listCryptoCategory = [
    "BTC",
    "ETH",
    "BNB",
    "USDT",
    "SOL",
    "XRP",
    "ADA",
    "USDC",
    "LUNA",
    "AVAX",
  ];

  List<String> listMobileOperator = [
    "Airtel money",
    "Orange money",
    "M-Pesa",
    "Western",
  ];

  List<String> listOfCountries = [
    'Afrique du Sud',
    'Algérie',
    'Angola',
    'Bénin',
    'Botswana',
    'Burkina Faso',
    'Burundi',
    'Cambodge',
    'Cameroun',
    'Cap-Vert',
    'République centrafricaine',
    'Comores',
    'République du Congo',
    'Congo(RDC)',
    "Côte d’Ivoire",
    'Djibouti',
    'Égypte',
    'Érythrée',
    'Eswatini',
    'Éthiopie',
    'Gabon',
    'Gambie',
    'Ghana',
    'Guinée',
    'Guinée-Bissau',
    'Guinée équatoriale',
    'Kenya',
    'Lesotho',
    'Liberia',
    'Libye',
    'Madagascar',
    'Malawi',
    'Mali',
    'Maroc',
    'Maurice',
    'Mauritanie',
    'Mozambique',
    'Namibie',
    'Niger',
    'Nigeria',
    'Ouganda',
    'Rwanda',
    'São Tomé-et-Principe',
    'Sénégal',
    'Seychelles',
    'Sierra Leone',
    'Somalie',
    'Soudan',
    'Soudan du Sud',
    'Tanzanie',
    'Tchad',
    'Togo',
    'Tunisie',
    'Zambie',
    'Zimbabwe',
  ];

}